# The APP_NAME variable determines the name of the final executable file. 
# It should
# not include any .exe postfix. If left blank the name will default to 
# the project name

APP_NAME = auto_proj

# The flags passed to xcc when building the application
# You can also set the following to override flags for a particular language:
#
#    XCC_XC_FLAGS, XCC_C_FLAGS, XCC_ASM_FLAGS, XCC_CPP_FLAGS
#
# If the variable XCC_MAP_FLAGS is set it overrides the flags passed to 
# xcc for the final link (mapping) stage.

CC_FLAGS = -Os -g


#=============================================================================
# The following part of the Makefile includes the common build infrastructure
# for compiling XMOS applications. You should not need to edit below here.


# Use the main Makefile from module_xmos_common
include ../../xcommon/module_xcommon/build/Makefile.pc

